import { SaaSPlan, SaaSClient, SaaSLicenseKey, SaaSPaymentTransaction, SaaSGlobalSettings, SaaSActivationRequest } from './saasTypes';

export const INITIAL_SAAS_PLANS: SaaSPlan[] = [
  {
    id: 'plan_trial',
    name: 'Gratuit',
    code: 'TRIAL',
    monthlyPriceFCFA: 0,
    monthlyPriceEUR: 0,
    maxClasses: 2,
    maxTeachers: 2,
    maxGenerations: 4,
    maxExports: 4,
    features: {
      pdfExport: true,
      excelExport: false,
      wordExport: false,
      geminiAI: false,
      prioritySupport: false,
      multiUser: false,
      customBranding: false,
    },
    description: 'Pour tester le générateur (2 classes, 2 profs, 4 générations & 4 exports PDF).',
    badgeText: 'Gratuit',
    wavePaymentUrl: 'https://pay.wave.com/m/M_SN_GESTSCOLAIRE_DECOUVERTE'
  },
  {
    id: 'plan_standard',
    name: 'Standard',
    code: 'STANDARD',
    monthlyPriceFCFA: 10000,
    monthlyPriceEUR: 15,
    maxClasses: 8,
    maxTeachers: 15,
    maxGenerations: 30,
    maxExports: 25,
    features: {
      pdfExport: true,
      excelExport: false,
      wordExport: false,
      geminiAI: false,
      prioritySupport: false,
      multiUser: false,
      customBranding: false,
    },
    description: 'Pour les petites structures (8 classes, 15 profs, 30 générations & 25 exports PDF).',
    badgeText: 'Standard',
    wavePaymentUrl: 'https://pay.wave.com/m/M_SN_GESTSCOLAIRE_PLAN_STANDARD'
  },
  {
    id: 'plan_premium',
    name: 'Premium',
    code: 'PREMIUM',
    monthlyPriceFCFA: 15000,
    monthlyPriceEUR: 23,
    maxClasses: 20,
    maxTeachers: 25,
    maxGenerations: 50,
    maxExports: 50,
    features: {
      pdfExport: true,
      excelExport: true,
      wordExport: true,
      geminiAI: true,
      prioritySupport: true,
      multiUser: false,
      customBranding: false,
    },
    popular: true,
    description: 'Pour collèges & lycées (20 classes, 25 profs, 50 générations & 50 exports Tout format).',
    badgeText: 'Recommandé',
    wavePaymentUrl: 'https://pay.wave.com/m/M_SN_GESTSCOLAIRE_PLAN_PREMIUM'
  },
  {
    id: 'plan_school',
    name: 'School',
    code: 'SCHOOL',
    monthlyPriceFCFA: 30000,
    monthlyPriceEUR: 46,
    maxClasses: 999,
    maxTeachers: 999,
    maxGenerations: 9999,
    maxExports: 9999,
    features: {
      pdfExport: true,
      excelExport: true,
      wordExport: true,
      geminiAI: true,
      prioritySupport: true,
      multiUser: true,
      customBranding: true,
    },
    description: 'Générations & Exportations illimitées, IA prioritaire, Custom Branding, Multi-comptes.',
    badgeText: 'Illimité & VIP',
    wavePaymentUrl: 'https://pay.wave.com/m/M_SN_GESTSCOLAIRE_PLAN_SCHOOL'
  }
];

export const INITIAL_SAAS_CLIENTS: SaaSClient[] = [
  {
    id: 'cli_01',
    schoolName: 'Lycée Lamine Guèye',
    logoIcon: 'GraduationCap',
    adminName: 'Mamadou Diallo',
    adminEmail: 'm.diallo@laminegueye.edu.sn',
    phone: '+221 77 654 32 10',
    cityCountry: 'Dakar, Sénégal',
    planId: 'plan_standard',
    status: 'active',
    startDate: '2025-09-01',
    trialEndDate: '2025-09-15',
    subscriptionEndDate: '2026-09-01',
    licenseKey: 'SCH-PRO-2025-LG99-8822',
    paymentMethod: 'Orange Money',
    totalPaidFCFA: 120000,
    createdAt: '2025-08-20',
    lastActiveAt: 'Aujourd\'hui 14:32',
    classesCount: 8,
    teachersCount: 15,
    notes: 'Paiement annuel reçu par Orange Money Pro.'
  },
  {
    id: 'cli_02',
    schoolName: 'Collège Saint-Michel',
    logoIcon: 'Building2',
    adminName: 'Sœur Marie-Claire',
    adminEmail: 'direction@st-michel.sn',
    phone: '+221 78 123 45 67',
    cityCountry: 'Dakar, Sénégal',
    planId: 'plan_premium',
    status: 'active',
    startDate: '2025-10-01',
    trialEndDate: '2025-10-15',
    subscriptionEndDate: '2026-10-01',
    licenseKey: 'SCH-PREM-2025-STM-1002',
    paymentMethod: 'Wave',
    totalPaidFCFA: 180000,
    createdAt: '2025-09-28',
    lastActiveAt: 'Hier 09:15',
    classesCount: 20,
    teachersCount: 25,
    notes: 'Grand établissement avec export Word/Excel et module IA activé.'
  },
  {
    id: 'cli_03',
    schoolName: 'Groupe Scolaire Bilingue Excellence',
    logoIcon: 'Award',
    adminName: 'Dr. Jean-Pascal Koffi',
    adminEmail: 'jp.koffi@excellence-edu.ci',
    phone: '+225 07 89 12 34',
    cityCountry: 'Abidjan, Côte d\'Ivoire',
    planId: 'plan_trial',
    status: 'trial',
    startDate: '2026-05-01',
    trialEndDate: '2026-05-15',
    subscriptionEndDate: '2026-05-15',
    paymentMethod: 'Gratuit',
    totalPaidFCFA: 0,
    createdAt: '2026-05-01',
    lastActiveAt: 'Aujourd\'hui 11:05',
    classesCount: 2,
    teachersCount: 2,
    notes: 'En évaluation active. Intéressé par le Plan Standard.'
  },
  {
    id: 'cli_04',
    schoolName: 'Lycée Thierno Seydou Nourou Tall',
    logoIcon: 'GraduationCap',
    adminName: 'Ousmane Sow',
    adminEmail: 'o.sow@tsnt.edu.sn',
    phone: '+221 76 998 87 76',
    cityCountry: 'Dakar, Sénégal',
    planId: 'plan_standard',
    status: 'expired',
    startDate: '2025-04-10',
    trialEndDate: '2025-04-24',
    subscriptionEndDate: '2026-04-10',
    licenseKey: 'SCH-PRO-2025-TSNT-5541',
    paymentMethod: 'Virement',
    totalPaidFCFA: 120000,
    createdAt: '2025-04-01',
    lastActiveAt: 'Il y a 5 jours',
    classesCount: 7,
    teachersCount: 12,
    notes: 'Abonnement expiré. Relance commerciale envoyée.'
  },
  {
    id: 'cli_05',
    schoolName: 'Institut Polytechnique de Thiès',
    logoIcon: 'BookOpen',
    adminName: 'Prof. Amadou Ndiaye',
    adminEmail: 'a.ndiaye@ipt.sn',
    phone: '+221 70 333 22 11',
    cityCountry: 'Thiès, Sénégal',
    planId: 'plan_school',
    status: 'active',
    startDate: '2025-11-15',
    trialEndDate: '2025-11-29',
    subscriptionEndDate: '2026-11-15',
    licenseKey: 'SCH-SCH-2025-IPT-9001',
    paymentMethod: 'Clé Licence',
    totalPaidFCFA: 360000,
    createdAt: '2025-11-10',
    lastActiveAt: 'Il y a 2h',
    classesCount: 45,
    teachersCount: 60,
    notes: 'Plan School illimité avec Custom Branding activé.'
  },
  {
    id: 'cli_06',
    schoolName: 'Sagesse Academy',
    logoIcon: 'Building2',
    adminName: 'Fatou Bintou Ndiaye',
    adminEmail: 'contact@sagesse-academy.com',
    phone: '+221 77 111 22 33',
    cityCountry: 'Saint-Louis, Sénégal',
    planId: 'plan_standard',
    status: 'suspended',
    startDate: '2025-06-01',
    trialEndDate: '2025-06-15',
    subscriptionEndDate: '2026-06-01',
    licenseKey: 'SCH-PRO-2025-SAG-1212',
    paymentMethod: 'Wave',
    totalPaidFCFA: 10000,
    createdAt: '2025-05-20',
    lastActiveAt: 'Il y a 12 jours',
    classesCount: 8,
    teachersCount: 15,
    notes: 'Accès suspendu pour litige de paiement mensuel.'
  }
];

export const INITIAL_SAAS_LICENSE_KEYS: SaaSLicenseKey[] = [
  {
    id: 'key_1',
    key: 'SCH-PRO-2026-X89K-912M',
    planId: 'plan_pro',
    durationDays: 365,
    generatedAt: '2026-05-01',
    status: 'unused'
  },
  {
    id: 'key_2',
    key: 'SCH-PREM-2026-VIP7-771B',
    planId: 'plan_premium',
    durationDays: 365,
    generatedAt: '2026-05-02',
    status: 'unused'
  },
  {
    id: 'key_3',
    key: 'SCH-PRO-2025-LG99-8822',
    planId: 'plan_pro',
    durationDays: 365,
    generatedAt: '2025-08-20',
    status: 'used',
    usedByClientId: 'cli_01',
    usedByClientName: 'Lycée Lamine Guèye',
    usedAt: '2025-09-01'
  },
  {
    id: 'key_4',
    key: 'SCH-PREM-2025-IPT-9001',
    planId: 'plan_premium',
    durationDays: 365,
    generatedAt: '2025-11-10',
    status: 'used',
    usedByClientId: 'cli_05',
    usedByClientName: 'Institut Polytechnique de Thiès',
    usedAt: '2025-11-15'
  }
];

export const INITIAL_SAAS_TRANSACTIONS: SaaSPaymentTransaction[] = [
  {
    id: 'tx_101',
    invoiceRef: 'INV-2026-0501',
    clientId: 'cli_01',
    clientName: 'Lycée Lamine Guèye',
    amountFCFA: 240000,
    amountEUR: 366,
    paymentMethod: 'Orange Money',
    status: 'completed',
    date: '2025-09-01',
    planName: 'Plan Établissement Pro',
    period: 'Annuel (2025-2026)'
  },
  {
    id: 'tx_102',
    invoiceRef: 'INV-2026-0502',
    clientId: 'cli_02',
    clientName: 'Collège Saint-Michel',
    amountFCFA: 520000,
    amountEUR: 790,
    paymentMethod: 'Wave',
    status: 'completed',
    date: '2025-10-01',
    planName: 'Plan Institutionnel Premium',
    period: 'Annuel (2025-2026)'
  },
  {
    id: 'tx_103',
    invoiceRef: 'INV-2026-0503',
    clientId: 'cli_05',
    clientName: 'Institut Polytechnique de Thiès',
    amountFCFA: 520000,
    amountEUR: 790,
    paymentMethod: 'Clé Licence',
    status: 'completed',
    date: '2025-11-15',
    planName: 'Plan Institutionnel Premium',
    period: 'Annuel (2025-2026)'
  },
  {
    id: 'tx_104',
    invoiceRef: 'INV-2026-0504',
    clientId: 'cli_06',
    clientName: 'Sagesse Academy',
    amountFCFA: 25000,
    amountEUR: 38,
    paymentMethod: 'Wave',
    status: 'completed',
    date: '2025-06-01',
    planName: 'Plan Établissement Pro',
    period: 'Mensuel (Juin 2025)'
  }
];

export const INITIAL_SAAS_SETTINGS: SaaSGlobalSettings = {
  maintenanceMode: false,
  globalAnnouncement: '🎉 Bienvenue sur la plateforme SaaS EdTech Emploi du Temps v1.4 ! Vous pouvez souscrire et payer par Wave pour tous les niveaux d\'abonnements.',
  announcementType: 'info',
  defaultTrialDays: 14,
  allowNewRegistrations: true,
  supportedPaymentGateways: {
    wave: true,
    orangeMoney: true,
    stripe: true,
    bankTransfer: true,
    licenseKey: true
  },
  contactEmail: 'admin-saas@edtech-emploidutemps.com',
  supportPhone: '+221 33 800 00 00',
  waveConfig: {
    merchantName: 'GestScolaire SaaS Pro / EduTech',
    merchantPhone: '+221 77 845 12 00',
    globalWaveUrl: 'https://pay.wave.com/m/M_SN_GESTSCOLAIRE_GLOBAL',
    qrCodeUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    instructions: 'Cliquez sur le bouton pour être redirigé vers l\'application Wave ou scannez le QR Code pour effectuer le règlement direct. Entrez la référence de transaction pour validation instantanée.'
  }
};

export const INITIAL_SAAS_ACTIVATION_REQUESTS: SaaSActivationRequest[] = [
  {
    id: 'req_01',
    type: 'new_activation',
    schoolName: 'Lycée Moderne de Rufisque',
    adminName: 'M. Abdoulaye Ba',
    adminEmail: 'a.ba@lyceerufisque.sn',
    whatsapp: '+221 77 456 78 90',
    cityCountry: 'Rufisque, Sénégal',
    planId: 'plan_premium',
    amountFCFA: 15000,
    durationMonths: 1,
    paymentMethod: 'Wave',
    status: 'pending',
    requestedAt: 'Aujourd\'hui 10:15',
    notes: 'Paiement Wave effectué via le lien direct. En attente de clé.'
  },
  {
    id: 'req_02',
    type: 'upgrade',
    clientId: 'cli_03',
    schoolName: 'Groupe Scolaire Bilingue Excellence',
    adminName: 'Dr. Jean-Pascal Koffi',
    adminEmail: 'jp.koffi@excellence-edu.ci',
    whatsapp: '+225 07 89 12 34',
    cityCountry: 'Abidjan, Côte d\'Ivoire',
    planId: 'plan_standard',
    amountFCFA: 10000,
    durationMonths: 1,
    paymentMethod: 'Wave',
    status: 'pending',
    requestedAt: 'Aujourd\'hui 11:30',
    notes: 'Demande de mise à niveau du Plan Gratuit vers le Plan Standard.'
  },
  {
    id: 'req_03',
    type: 'new_activation',
    schoolName: 'Collège Privé Mariama Bâ',
    adminName: 'Mme Aïda Fall',
    adminEmail: 'aida.fall@mariamaba.edu.sn',
    whatsapp: '+221 76 888 99 00',
    cityCountry: 'Gorée, Sénégal',
    planId: 'plan_school',
    amountFCFA: 30000,
    durationMonths: 1,
    paymentMethod: 'Wave',
    status: 'delivered',
    requestedAt: 'Hier 16:45',
    deliveredAt: 'Hier 17:00',
    assignedKey: 'SCH-SCH-2026-MBA-7741',
    notes: 'Clé transmise et activée avec succès par WhatsApp.'
  }
];
